Android Data Binding
This adds data binding to Android. It is not 100% complete, but should be sufficient for most use cases. Outstanding work detailed below.

Largely sticks to a 1:1 API with C++. Some methods duplicated on instances from VMs were not implemented in favor of simplicity and "one correct way".

In the case of iterable enums and properties, the JNI bindings construct Kotlin objects from C++.

RiveDataBindingTest has the tests and demonstrates use.

## Todo
- [ ] Need a sample in the examples app. (Can fast follow)
- [ ] Need to investigate controller serialization interaction with data binding
- [x] Could strengthen documentation. Please point out areas that are weak.
- [x] Could add more unit test coverage. Open to suggestions.
- [x] Need to make a transfer object so that instances can outlive files
- [x] Fix trigger tests - both observing and simple firing
- [x] ~Use native Android Color type~ (Not available pre-API 26)
- [x] Failing unit test - `default_instance`.
  - `expected:<Test [Default]> but was:<Test [Alternate]>`
  - Tracked [on Slack here](https://2dimensions.slack.com/archives/C07MPAN5FDE/p1738718337635749)
- [x] Failing unit test - `blank_instance`.
  - `expected:<0> but was:<-14869219>`
  - Tracked [on Slack here](https://2dimensions.slack.com/archives/C07MPAN5FDE/p1738719178866969)
- [x] No callbacks yet for properties.
- [x] Add binding to assign instance to state machines
- [x] Add a getter to the state machine for the assigned instance
- [x] Need to figure out ViewModelInstance lifetimes. They're documented as the user's responsibility, but they also get added to the File as a dependency, so maybe not that big of a deal after all and the warnings need to be toned down
- [x] Need to figure out if dependencies (i.e. hierarchical reference counting) is being used too liberally. If certain methods are called in a loop, would it unnecessarily accumulate memory?
- [x] Check for memory leaks

Diffs=
b0e6cc5388 feat: Android Data Binding (#8973)

Co-authored-by: Erik <erik@rive.app>
Co-authored-by: Umberto Sonnino <umberto@rive.app>